### ISSUE TITLE
Missing header file

### ISSUE THREAD

**Issue by msyriac** [AdriJD/optweight#1]
The header file here:
https://github.com/AdriJD/optweight/blob/a234a9550e1af19afd660ab780d3bfe7d2546bdc/src/optweight_alm_c_utils.c#L1

"optweight_alm_c_utils_test.h" is missing. Perhaps this was referring to "optweight_alm_c_utils.h" ?

**Comment by AdriJD** [comment]
Ah yes it should have. Thanks for spotting that! I pushed a change.
