### ISSUE TITLE
Biased noise models for "small" fwhm_fact

### ISSUE THREAD

**Issue by zatkins2** [AdriJD/optweight#9]
There is an unexpected phenomenon when fwhm_factors are "too small" that leads to a biased (too large) noise model. The root cause is the smoothing implementation (in harmonic space) combined with the "near_psd" operations that zero-out any negative pixel values. If the Gaussian beam does not sufficiently die-off at the lmax of the covariance wavelet map, the smoothed covariance will "ring" and have some negative values that get set to 0 after the smoothing. The ring's positive errors, though, don't get subtracted, and so effectively the smoothed covariance gets extra power. For a realistic ACT TT noise power spectrum, these were the observed biases (assuming totally isotropic noise):

0.2% at fwhm_fact=2
0.4% at fwhm_fact=1
2.7% at fwhm_fact=0.5
4.5% at fwhm_fact=0 (nominal no smoothing)

I confirmed this came from the smoothing alone by commenting out the call to `map_utils.lmul_pix` in `noise_utils.estimate_cov_pix` for the fwhm_fact=0 case and the bias went away. 

These factors aren't something we'd normally encounter; however, when this bias kicks in will depend on what the actual noise looks like. Good to know we haven't seen it so far e.g. in SO TOD sims.

I think the way around this bias would be ~~to not smooth with a Gaussian kernel, but rather with a kernel that always goes to 0 by the lmax of the wavelet map~~ no, this won't help. Alternatively, one could smooth directly in wavelet map space, but then the physical kernel size varies over declination (this is what happens in directional wavelet model, for instance). Or somehow correct a map depending on how much power was added in the "near_psd" step (ie, reset monopole of smoothed map to what it was before any near_psd stuff).

**Comment by zatkins2** [comment]
#10 fixes simplest thing: if fwhm=0.

**Comment by AdriJD** [comment]
Thanks Zach! This makes sense, although I had not expected it to be such a large effect. Still, like you said, this should not matter for normal use and thus I think we should leave this for now (except for the small fix you added, which is fine to add).
